In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd
import urllib
import tarfile

In [2]:
url = 'https://github.com/le-scientifique/torchDatasets/raw/master/dbpedia_csv.tar.gz'

def getunzipped(theurl):
    name = './dbpedia_csv.tar.gz'
    try:
        name, hdrs = urllib.request.urlretrieve(theurl, name)
    except IOError as e:
        print("Can't retrieve %r to %r: %s" % (theurl, thedir, e))
        return
    try:
        z = tarfile.open(name, "r:gz")
        z.extractall()
        z.close()
    except tarfile.error as e:
        print("Bad zipfile (from %r): %s" % (theurl, e))
        return

    print("Data Downloaded and unzipped!")

In [3]:
getunzipped(url)

Data Downloaded and unzipped!


In [2]:
train = pd.read_csv('dbpedia_csv/train.csv',header=None,names=['class','title','text'])
print(train.shape)
train.head()

(560000, 3)


class                              title  \
0      1                   E. D. Abbott Ltd   
1      1                     Schwan-Stabilo   
2      1                         Q-workshop   
3      1  Marvell Software Solutions Israel   
4      1        Bergan Mercy Medical Center   

                                                text  
0   Abbott of Farnham E D Abbott Limited was a Br...  
1   Schwan-STABILO is a German maker of pens for ...  
2   Q-workshop is a Polish company located in Poz...  
3   Marvell Software Solutions Israel known as RA...  
4   Bergan Mercy Medical Center is a hospital loc...

In [3]:
test = pd.read_csv('dbpedia_csv/test.csv',header=None,names=['class','title','text'])
test.head()

class                     title  \
0      1                     TY KU   
1      1     Odd Lot Entertainment   
2      1                    Henkel   
3      1                GOAT Store   
4      1  RagWing Aircraft Designs   

                                                text  
0   TY KU /taɪkuː/ is an American alcoholic bever...  
1   OddLot Entertainment founded in 2001 by longt...  
2   Henkel AG & Company KGaA operates worldwide w...  
3   The GOAT Store (Games Of All Type Store) LLC ...  
4   RagWing Aircraft Designs (also called the Rag...

In [4]:
X_train = train['text'].get_values()
X_test = test['text'].get_values()
y_train = train['class'].get_values()
y_test= test['class'].get_values()

In [5]:
max_doc_length = 50

train_lengths = train['text'].apply(lambda x: min(max_doc_length, len(x.split(' '))))
test_lengths = test['text'].apply(lambda x: min(max_doc_length, len(x.split(' '))))

In [6]:
train_lengths = train_lengths.values
test_lengths = test_lengths.values

### VocabularyProcessor 
Has an sklearn type interface - instantiate, call .fit() and .transform()

Creates a mapping between words and ID's.

Fit creates the mapping word-> ID, and transform replaces the words with relevant IDS.

We can then use tf.nn.embedding_lookup(...) to look up the vector representations that correspond to each ID.

In [7]:
preprocessor = tf.contrib.learn.preprocessing.VocabularyProcessor(max_doc_length, min_frequency=3)

In [8]:
X_train_transformed = np.array(list(preprocessor.fit_transform(X_train)))

As you can see, we have replaced each word with a numerical ID corresponding to a word in our vocabulary

In [9]:
X_train_transformed

array([[  8857,      3,  17539, ...,      0,      0,      0],
       [     0,      4,      5, ...,      0,      0,      0],
       [     0,      4,      5, ...,      9, 114800,      0],
       ..., 
       [     8,      0,   6291, ...,      0,      0,      0],
       [     0,  71320,   4408, ...,      3,    686,      0],
       [ 12952,   9652,  53503, ...,  14682,    595,  12709]], dtype=int64)

In [10]:
print("The word 'the' corresponds to ID:",preprocessor.vocabulary_.get('the')) #Get the ID for a word
print("ID 25 corresponds to:",preprocessor.vocabulary_.reverse(25)) #Get the word that corresponds to an ID

The word 'the' corresponds to ID: 1
ID 25 corresponds to: known


In [11]:
vocab_length = len(preprocessor.vocabulary_)

In [12]:
X_test_transformed = np.array(list(preprocessor.transform(X_test)))

In [13]:
X_test_transformed[:2]

array([[     0,  33095,      0,      4,     15,     34,  13638,  12026,
            58,     32,   2092,      2,  34220,      6,    154,  19432,
             8,      0,     58,      7,    108,      2,    254,      6,
             4,    672,      2,     46,    111,    133,     46,    111,
          1789,     69,      2,     46,    111,      0,  33095,   1012,
         12873,     40,    218,      2,    342,    137,      5,   2554,
          2603,     17],
       [  7874,  13438,   1130,    108,      2,    346,      9,   5924,
          3640,  26563,  53628,      6,   9446,   4389, 115134,      8,
         10402, 102537,      4,      5,     22,    454,      6,  11213,
            58,     69,      2,  14655,    133,    144,   7874,  13438,
           138,      1,     22,    579,      3,   9822,   1198,  38006,
         13657,     82,  27928,   2842,     56,     22,    579,      3,
           155,     82]], dtype=int64)

In [14]:
next(preprocessor.reverse(X_train_transformed[0,None].tolist()))

'Abbott of Farnham E D Abbott Limited was a British coachbuilding business based in Farnham Surrey trading under that name from 1929 A major part of their output was under sub-contract to motor vehicle manufacturers Their business closed in 1972 <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK> <UNK>'

### Now our data is prepared we can start modelling...

The basics have been implemented, but you need to implement the RNN functionality, and define the loss function.

As a starting point, you several comments have been provided in the relevant name scopes.

In [163]:
graph = tf.Graph()
embedding_size=100
rnn_cell_size = 100
n_classes=15
learning_rate = 0.005

with graph.as_default(), tf.device('/cpu:0'):
    with tf.name_scope('placeholders'):
        tf_X = tf.placeholder(shape=[None, max_doc_length], dtype=tf.int32) #This is a matrix of word IDs
        tf_y = tf.placeholder(shape=[None], dtype=tf.int64) #This is a list of class labels e.g. 1,5,3 etc.
        tf_lengths = tf.placeholder(shape=[None,], dtype=tf.int32) #This is the lengths 
                                                                    #of each document in sample
        
    with tf.name_scope('variables'):
        embeddings = tf.Variable(tf.random_uniform([vocab_length,embedding_size],-1.0,1.0)) 
        W = tf.Variable(tf.truncated_normal(shape=[rnn_cell_size, n_classes ]))
        b = tf.Variable(tf.random_uniform(shape=[n_classes,]))
        tf_y_one_hot = tf.one_hot(tf_y,n_classes)
    
    with tf.name_scope('embbeding_lookup'):
        #You need to look up the word ID and get replace with the associated word vector.
        #Verify the size is (?, max_doc_length, embedding_size)
        tf_X_embedded = tf.nn.embedding_lookup(embeddings, tf_X) 
        
    with tf.name_scope('run_rnn'):
        #You need to define a cell type - use GRUCell
        #Also need to feed data into the RNN and get the final_state - use dynamic_rnn
        cell = tf.contrib.rnn.BasicRNNCell(rnn_cell_size)
        outputs, final_state = tf.nn.dynamic_rnn(cell,tf_X_embedded, tf_lengths, dtype=tf.float32)
        
    with tf.name_scope('attention'):
        #The most complex part of this is the multiplication - TF doesn't have a nice way to handle 3d by 2d.
        
        #attention Variables
        W_a1 = tf.Variable(tf.random_uniform(shape=[rnn_cell_size,1]))
        b_a1 = tf.Variable(tf.random_uniform(shape=[1,]))
        W_a2 = tf.Variable(tf.random_uniform(shape=[max_doc_length,max_doc_length]))
        b_a2 = tf.Variable(tf.random_uniform(shape=[max_doc_length,]))
        
        #Basicly a 1 hidden layer MLP to compute attention
        reshape_out= tf.reshape(outputs, [-1, rnn_cell_size])
        wo = tf.matmul(reshape_out, W_a1)
        attn_hidden = tf.nn.tanh(tf.reshape(wo, [-1, max_doc_length])+b_a1)
        attn_output = tf.nn.softmax(tf.matmul(attn_hidden, W_a2)+b_a2)
        a = tf.expand_dims(attn_output,-1)
        
        #weighted average state using attention
        attn_state = tf.reduce_sum(tf.multiply(a, outputs), axis=1)
        
        
    with tf.name_scope('output_layer'):
        #Create a variable logits which is final_state * W + b
        #Pass this through a softmax to create prediction probabilities.
        logits = tf.matmul(attn_state,W)+b
        predictions=tf.argmax(tf.nn.softmax(logits),1)
        
    with tf.name_scope('loss'):
        #Add a loss and an optimizer
        loss= tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=logits, labels=tf_y_one_hot))
        optimizer = tf.train.AdamOptimizer(learning_rate).minimize(loss)
        
    with tf.name_scope('validation'):
        correct_prediction = tf.equal(tf_y, predictions)
        accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    
        
    with tf.name_scope('init'):
        init_op = tf.global_variables_initializer()

In [126]:
batch_size = 128
print_step = 150
from tqdm import tqdm

with tf.Session(graph=graph) as session:
    number_of_steps = 301
    train_indicies = np.arange(X_train_transformed.shape[0])
    test_indicies = np.arange(X_test_transformed.shape[0])
    
    session.run(init_op)
    average_loss = 0
    
    for step in tqdm(range(number_of_steps)):
        ind =  np.random.choice(np.arange(X_train_transformed.shape[0]), batch_size)
        feed_dict = {tf_X:X_train_transformed[ind], 
                     tf_y:y_train[ind], 
                     tf_lengths: train_lengths[ind] }
        l,_ = session.run([loss,optimizer ], feed_dict=feed_dict)
        average_loss+=l
        
        if step%print_step == 0:
            print ("average loss:",average_loss/print_step)
            ind2 =  np.random.choice(np.arange(X_test_transformed.shape[0]), batch_size*200)
            test_dict = {tf_X:X_test_transformed[ind2], 
                     tf_y:y_test[ind2], 
                     tf_lengths: test_lengths[ind2] }
            print("accuracy",accuracy.eval(feed_dict=test_dict))
            print('-'*40, "step "+str(step), '-'*40)
            
            average_loss=0
    test_dict = {tf_X:X_test_transformed[5:30], 
                     tf_y:y_test[5:30], 
                     tf_lengths: test_lengths[5:30] }
    attn = a.eval(feed_dict=test_dict)

  0%|                                                                                          | 0/301 [00:00<?, ?it/s]

average loss: 0.0234767452876
accuracy 0.0797266
---------------------------------------- step 0 ----------------------------------------


 50%|███████████████████████████████████████▊                                        | 150/301 [00:52<00:47,  3.17it/s]

average loss: 1.39103110154
accuracy 0.840586
---------------------------------------- step 150 ----------------------------------------


100%|███████████████████████████████████████████████████████████████████████████████▋| 300/301 [01:44<00:00,  3.18it/s]

average loss: 0.367573136389
accuracy 0.921523
---------------------------------------- step 300 ----------------------------------------


100%|████████████████████████████████████████████████████████████████████████████████| 301/301 [01:50<00:00,  1.89s/it]


In [158]:
doc = 11
phrase = next(preprocessor.reverse(X_test_transformed[doc,None].tolist()))

In [159]:
np.argsort(attn[doc].ravel())

array([45, 27, 38, 35, 42, 46, 40, 23, 31, 24,  1, 48, 19, 43, 49,  2, 22,
        4, 36, 14, 30, 32, 25, 44, 37, 20, 47, 26, 15, 34, 16, 41,  0,  3,
       33, 21, 18, 39,  7, 17,  5, 12, 28, 29,  8, 10,  6, 13,  9, 11], dtype=int64)

In [162]:
from IPython.core.display import HTML
out= ''
for i, word in enumerate(X_test_transformed[doc]):
    r_word = preprocessor.vocabulary_.reverse(word)
    if r_word == '<UNK>':
        r_word = '	&#60;UNK>'
    if i in np.argsort(attn[doc].ravel())[-5:]:
        out += '<b>'+ r_word + '</b> '
    else:
        out += r_word + ' '
HTML(out)